Resources:
  WebDMZSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable Web Access 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          Cidrlp: 0.0.0.0/0 # access from anywhere in the world
  WebServerEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0b898040803850657
      Tags:
        - Key: Name
          Value: WebServer01
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: CloudFormation-Bucket-ColinBut
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: Index.html
