Resources:
  WebServerEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0b898040803850657
      Tags:
        - Key: Name
          Value: WebServer01
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: CloudFormation-Bucket-ColinBut
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: Index.html
