Resources:
  WebServerEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0d8e27447ec2c8410 # EU (London)
      Tags:
        - Key: Name
          Value: WebServer01
        - Key: "Details"
          Value: !Join
            - ""
            - - "EC2 Instance for "
              - !Ref AWS::Region
      SecurityGroups:
        - !Ref WebDMZSecurityGroup
  WebDMZSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable Web Access 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0 # access from anywhere in the world
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
